=== AdriMG10/AdrianMerino_UD4_LMSGI/Editorial/game.dtd
<!ELEMENT informe (cabecera, datos)>
<!ELEMENT cabecera (titulo, subtitulo, descripcion, fecha)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT datos (plataforma+, trimestre, juegosVendidos)>
<!ELEMENT plataforma (playstation, xbox, nintendo)>
<!ELEMENT playstation (#PCDATA | trimestreD | juegosVendidosD)*>
<!ELEMENT xbox (#PCDATA | trimestreD | juegosVendidosD)*>
<!ELEMENT nintendo (#PCDATA | trimestreD | juegosVendidosD)*>
<!ELEMENT trimestreD (#PCDATA)>
<!ELEMENT juegosVendidosD (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT juegosVendidos (#PCDATA)>

=== AdriMG10/AdrianMerino_UD4_LMSGI/Editorial/game.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE informe SYSTEM "game.dtd">
<informe>
    <cabecera>
        <titulo>GAME</titulo>
        <subtitulo>Informe ventas juegos anuales C.C. Area Sur</subtitulo>
        <descripcion>Descripci√≥n: informe de ventas de juegos en GAME C.C. Area Sur 2022</descripcion>
        <fecha>Fecha del informe: 31/01/2023</fecha>
    </cabecera>
    <datos>
        <plataforma>
            <playstation>PlayStation
                <trimestreD>1</trimestreD>
                <juegosVendidosD>3543</juegosVendidosD>
                <trimestreD>2</trimestreD>
                <juegosVendidosD>2498</juegosVendidosD>
                <trimestreD>3</trimestreD>
                <juegosVendidosD>3145</juegosVendidosD>
                <trimestreD>4</trimestreD>
                <juegosVendidosD>5432</juegosVendidosD>
            </playstation> 
            <xbox>Xbox
                <trimestreD>1</trimestreD>
                <juegosVendidosD>713</juegosVendidosD>
                <trimestreD>2</trimestreD>
                <juegosVendidosD>543</juegosVendidosD>
                <trimestreD>3</trimestreD>
                <juegosVendidosD>674</juegosVendidosD>
                <trimestreD>4</trimestreD>
                <juegosVendidosD>872</juegosVendidosD>
            </xbox>
            <nintendo>Nintendo
                <trimestreD>1</trimestreD>
                <juegosVendidosD>4321</juegosVendidosD>
                <trimestreD>2</trimestreD>
                <juegosVendidosD>3457</juegosVendidosD>
                <trimestreD>3</trimestreD>
                <juegosVendidosD>5342</juegosVendidosD>
                <trimestreD>4</trimestreD>
                <juegosVendidosD>6789</juegosVendidosD>
            </nintendo>
        </plataforma>
        <trimestre>Trimestre</trimestre>
        <juegosVendidos>Juegos Vendidos</juegosVendidos>
    </datos>
</informe>
