<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca 
[
<!ELEMENT biblioteca (Libros*)>
<!ELEMENT Libros (Libro*)>
<!ELEMENT Libro (CodigoLibro, Autores, Titulo, Editorial, Edicion, Numeropgs, ISBN, FechaPublicacion)>
<!ELEMENT CodigoLibro (#PCDATA)>
<!ELEMENT Autores (Autor*)>
<!ELEMENT Autor (Nombre, Apellido1, Apellido2)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellido1 (#PCDATA)>
<!ELEMENT Apellido2 (#PCDATA)>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Editorial (#PCDATA)>
<!ELEMENT Edicion (#PCDATA)>
<!ELEMENT Numeropgs (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT FechaPublicacion (Dia, Mes, Anyo)>
<!ELEMENT Dia (#PCDATA)>
<!ELEMENT Mes (#PCDATA)>
<!ELEMENT Anyo (#PCDATA)>
]>

<biblioteca>
    <Libros>
        <Libro>
            <CodigoLibro>00001</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Brandon</Nombre>
                    <Apellido1>Winn</Apellido1>
                    <Apellido2>Sanderson</Apellido2>
                </Autor>
            </Autores>
            <Titulo>El imperio final</Titulo>
            <Editorial>Nova</Editorial>
            <Edicion>8</Edicion>
            <Numeropgs>688</Numeropgs>
            <ISBN>978-8417347291</ISBN>
            <FechaPublicacion>
                <Dia>19</Dia>
                <Mes>04</Mes>
                <Anyo>2018</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00002</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Antoine Marie</Nombre>
                    <Apellido1>Jean-Baptiste</Apellido1>
                    <Apellido2>Roger</Apellido2>
                </Autor>
            </Autores>
            <Titulo>El Principito</Titulo>
            <Editorial>Salamandra</Editorial>
            <Edicion>5</Edicion>
            <Numeropgs>96</Numeropgs>
            <ISBN>978-8498381498</ISBN>
            <FechaPublicacion>
                <Dia>18</Dia>
                <Mes>01</Mes>
                <Anyo>2008</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00003</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Fernando</Nombre>
                    <Apellido1>Rojas</Apellido1>
                    <Apellido2>Calderón</Apellido2>
                </Autor>
            </Autores>
            <Titulo>La Celestina</Titulo>
            <Editorial>Vicens Vives</Editorial>
            <Edicion>15</Edicion>
            <Numeropgs>256</Numeropgs>
            <ISBN>978-8431615116</ISBN>
            <FechaPublicacion>
                <Dia>04</Dia>
                <Mes>07</Mes>
                <Anyo>2013</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00004</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Angel</Nombre>
                    <Apellido1>Martín</Apellido1>
                    <Apellido2>Gomez</Apellido2>
                </Autor>
            </Autores>
            <Titulo>Por si las voces vuelven</Titulo>
            <Editorial>Planeta</Editorial>
            <Edicion>3</Edicion>
            <Numeropgs>256</Numeropgs>
            <ISBN>978-8408249214</ISBN>
            <FechaPublicacion>
                <Dia>17</Dia>
                <Mes>11</Mes>
                <Anyo>2021</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00005</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>George</Nombre>
                    <Apellido1>Raymond</Apellido1>
                    <Apellido2>Martin</Apellido2>
                </Autor>
            </Autores>
            <Titulo>Tormenta de espadas</Titulo>
            <Editorial>Vintage Espanol</Editorial>
            <Edicion>23</Edicion>
            <Numeropgs>1172</Numeropgs>
            <ISBN>978-1644735831</ISBN>
            <FechaPublicacion>
                <Dia>17</Dia>
                <Mes>05</Mes>
                <Anyo>2022</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00006</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>José</Nombre>
                    <Apellido1>Calvo</Apellido1>
                    <Apellido2>Poyato</Apellido2>
                </Autor>
            </Autores>
            <Titulo>La travesía Final</Titulo>
            <Editorial>HarperCollins</Editorial>
            <Edicion>2</Edicion>
            <Numeropgs>672</Numeropgs>
            <ISBN>978-8491396161</ISBN>
            <FechaPublicacion>
                <Dia>14</Dia>
                <Mes>04</Mes>
                <Anyo>2021</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00007</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>George</Nombre>
                    <Apellido1>Orwell</Apellido1>
                    <Apellido2></Apellido2>
                </Autor>
            </Autores>
            <Titulo>Rebelión en la granja</Titulo>
            <Editorial>DEBOLSILLO</Editorial>
            <Edicion>12</Edicion>
            <Numeropgs>144</Numeropgs>
            <ISBN>978-8499890951</ISBN>
            <FechaPublicacion>
                <Dia>07</Dia>
                <Mes>03</Mes>
                <Anyo>2013</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00008</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Raymond</Nombre>
                    <Apellido1>Douglas</Apellido1>
                    <Apellido2>Bradbury</Apellido2>
                </Autor>
            </Autores>
            <Titulo>Fahrenheit 451</Titulo>
            <Editorial>DEBOLSILLO</Editorial>
            <Edicion>5</Edicion>
            <Numeropgs>192</Numeropgs>
            <ISBN>978-8466356718</ISBN>
            <FechaPublicacion>
                <Dia>03</Dia>
                <Mes>06</Mes>
                <Anyo>2021</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00009</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Frank</Nombre>
                    <Apellido1>Patrick</Apellido1>
                    <Apellido2>Herbert</Apellido2>
                </Autor>
            </Autores>
            <Titulo>Dune</Titulo>
            <Editorial>DEBOLSILLO</Editorial>
            <Edicion>7</Edicion>
            <Numeropgs>784</Numeropgs>
            <ISBN>978-8466353779</ISBN>
            <FechaPublicacion>
                <Dia>04</Dia>
                <Mes>03</Mes>
                <Anyo>2021</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00010</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Robert</Nombre>
                    <Apellido1>Jordan</Apellido1>
                    <Apellido2></Apellido2>
                </Autor>
            </Autores>
            <Titulo>La Rueda del Tiempo: El ojo del mundo</Titulo>
            <Editorial>Planeta</Editorial>
            <Edicion>9</Edicion>
            <Numeropgs>832</Numeropgs>
            <ISBN>978-8445007006</ISBN>
            <FechaPublicacion>
                <Dia>15</Dia>
                <Mes>10</Mes>
                <Anyo>2019</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00011</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Dolores</Nombre>
                    <Apellido1>Redondo</Apellido1>
                    <Apellido2></Apellido2>
                </Autor>
            </Autores>
            <Titulo>Esperando al diluvio</Titulo>
            <Editorial>Ediciones Destino</Editorial>
            <Edicion>1</Edicion>
            <Numeropgs>588</Numeropgs>
            <ISBN>978-84566007006</ISBN>
            <FechaPublicacion>
                <Dia>16</Dia>
                <Mes>11</Mes>
                <Anyo>2022</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00012</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Juan</Nombre>
                    <Apellido1>Gómez</Apellido1>
                    <Apellido2>Jurado</Apellido2>
                </Autor>
            </Autores>
            <Titulo>Todo arde</Titulo>
            <Editorial>B</Editorial>
            <Edicion>1</Edicion>
            <Numeropgs>600</Numeropgs>
            <ISBN>978-8466672474</ISBN>
            <FechaPublicacion>
                <Dia>18</Dia>
                <Mes>10</Mes>
                <Anyo>2022</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00013</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Ildefonso</Nombre>
                    <Apellido1>Falcones</Apellido1>
                    <Apellido2></Apellido2>
                </Autor>
            </Autores>
            <Titulo>Esclava de la libertad</Titulo>
            <Editorial>GRIJALBO</Editorial>
            <Edicion>4</Edicion>
            <Numeropgs>624</Numeropgs>
            <ISBN>978-8425361791</ISBN>
            <FechaPublicacion>
                <Dia>30</Dia>
                <Mes>08</Mes>
                <Anyo>2022</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00014</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Artuto</Nombre>
                    <Apellido1>Pérez</Apellido1>
                    <Apellido2>Reverte</Apellido2>
                </Autor>
            </Autores>
            <Titulo>El italiano</Titulo>
            <Editorial>ALFAGUARA</Editorial>
            <Edicion>8</Edicion>
            <Numeropgs>400</Numeropgs>
            <ISBN>978-8420460499</ISBN>
            <FechaPublicacion>
                <Dia>21</Dia>
                <Mes>09</Mes>
                <Anyo>2021</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00015</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre></Nombre>
                    <Apellido1></Apellido1>
                    <Apellido2></Apellido2>
                </Autor>
            </Autores>
            <Titulo>Violeta</Titulo>
            <Editorial>PLAZA JANES</Editorial>
            <Edicion>5</Edicion>
            <Numeropgs>400</Numeropgs>
            <ISBN>978-8401027475</ISBN>
            <FechaPublicacion>
                <Dia>25</Dia>
                <Mes>01</Mes>
                <Anyo>2022</Anyo>
            </FechaPublicacion>
        </Libro>
        <Libro>
            <CodigoLibro>00016</CodigoLibro>
            <Autores>
                <Autor>
                    <Nombre>Pilar</Nombre>
                    <Apellido1>Eyre</Apellido1>
                    <Apellido2>Estrada</Apellido2>
                </Autor>
            </Autores>
            <Titulo>Cuando éramos ayer</Titulo>
            <Editorial>Planeta</Editorial>
            <Edicion>3</Edicion>
            <Numeropgs>368</Numeropgs>
            <ISBN>978-8408254737</ISBN>
            <FechaPublicacion>
                <Dia>23</Dia>
                <Mes>03</Mes>
                <Anyo>2022</Anyo>
            </FechaPublicacion>
        </Libro>
    </Libros>
</biblioteca>