=== AdriMG10/AdrianMerino_UD4_LMSGI/Clientes/clientes.dtd
<!ELEMENT clientes (sede+)>
<!ELEMENT sede (direccion+, nombreEmpleado, fechaAlta, cliente*)>
<!ATTLIST sede codigo CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombreEmpleado (#PCDATA)>
<!ELEMENT fechaAlta (#PCDATA)>
<!ELEMENT cliente (descripcion?, numViviendas, costeViviendas, resumenViviendas, plazoHacienda)>
<!ATTLIST cliente codigo CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numViviendas (#PCDATA)>
<!ELEMENT costeViviendas (#PCDATA)>
<!ELEMENT resumenViviendas (#PCDATA)>
<!ELEMENT plazoHacienda (#PCDATA)>

=== AdriMG10/AdrianMerino_UD4_LMSGI/Clientes/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="A0000001">
        <direccion>Calle Muñoz Vázquez, 17</direccion>
        <nombreEmpleado>Lucas Soto Téllez</nombreEmpleado>
        <fechaAlta>2007-10-05</fechaAlta>
        <cliente codigo="AAA-001">
            <descripcion>solvente</descripcion>
            <numViviendas>2</numViviendas>
            <costeViviendas>195000</costeViviendas>
            <resumenViviendas>Unifamiliares construcción el cementerio</resumenViviendas>
            <plazoHacienda>4</plazoHacienda>
        </cliente>
        <cliente codigo="AAA-002">
            <descripcion>solvente</descripcion>
            <numViviendas>1</numViviendas>
            <costeViviendas>55000</costeViviendas>
            <resumenViviendas>Piso nueva construcción</resumenViviendas>
            <plazoHacienda>12</plazoHacienda>
        </cliente>
        <cliente codigo="AAA-003">
            <descripcion>insolvente</descripcion>
            <numViviendas>3</numViviendas>
            <costeViviendas>185000</costeViviendas>
            <resumenViviendas>Parcelas el Portichuelo</resumenViviendas>
            <plazoHacienda>8</plazoHacienda>
        </cliente>
    </sede>
    <sede codigo="A0000002">
        <direccion>Calle Corredera, 50</direccion>
        <nombreEmpleado>Joaquín Salas Palacios</nombreEmpleado>
        <fechaAlta>2011-02-09</fechaAlta>
        <cliente codigo="BAA-001">
            <descripcion>solvente</descripcion>
            <numViviendas>5</numViviendas>
            <costeViviendas>545000</costeViviendas>
            <resumenViviendas>Apartamentos paseo marítimo</resumenViviendas>
            <plazoHacienda>5</plazoHacienda>
        </cliente>
        <cliente codigo="BAA-002">
            <descripcion>insolvente</descripcion>
            <numViviendas>2</numViviendas>
            <costeViviendas>220000</costeViviendas>
            <resumenViviendas>Adosados del Mesón</resumenViviendas>
            <plazoHacienda>2</plazoHacienda>
        </cliente>
        <cliente codigo="BAA-003">
            <descripcion>solvente</descripcion>
            <numViviendas>6</numViviendas>
            <costeViviendas>485000</costeViviendas>
            <resumenViviendas>Edificio de pisos del Paseo</resumenViviendas>
            <plazoHacienda>10</plazoHacienda>
        </cliente>
    </sede>
</clientes>
