=== AdriMG10/AdrianMerino_UD4_LMSGI/BDsms/BDsixcollection.dtd
<!ELEMENT BDsixcollection (sixcollection*)>
<!ELEMENT sixcollection (id, nombre, codigojuego, serie, pvp, aniolanzamiento)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigojuego (#PCDATA)>
<!ELEMENT serie (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>
<!ELEMENT aniolanzamiento (#PCDATA)>

=== AdriMG10/AdrianMerino_UD4_LMSGI/BDsms/BDsixcollection.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE BDsixcollection SYSTEM "BDsixcollection.dtd">
<BDsixcollection>
    <sixcollection>
        <id>1</id>
        <nombre>Ash</nombre>
        <codigojuego>198565412</codigojuego>
        <serie>1</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2015</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>2</id>
        <nombre>Montagne</nombre>
        <codigojuego></codigojuego>
        <serie>1</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2015</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>3</id>
        <nombre>IQ</nombre>
        <codigojuego></codigojuego>
        <serie>1</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2015</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>4</id>
        <nombre>Smoke</nombre>
        <codigojuego>842519663</codigojuego>
        <serie>1</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2015</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>5</id>
        <nombre>Tachanka</nombre>
        <codigojuego>985416357</codigojuego>
        <serie>1</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2015</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>6</id>
        <nombre>Sledge</nombre>
        <codigojuego>436788547</codigojuego>
        <serie>2</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2016</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>7</id>
        <nombre>Valkyrie</nombre>
        <codigojuego>573797885</codigojuego>
        <serie>2</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2016</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>8</id>
        <nombre>Thermite</nombre>
        <codigojuego>480654147</codigojuego>
        <serie>2</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2016</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>9</id>
        <nombre>JÃ¤ger</nombre>
        <codigojuego>619443880</codigojuego>
        <serie>2</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2016</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>10</id>
        <nombre>Hibana</nombre>
        <codigojuego>932259449</codigojuego>
        <serie>2</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2016</aniolanzamiento>
    </sixcollection> 
    <sixcollection>
        <id>11</id>
        <nombre>Bandit</nombre>
        <codigojuego>171399054</codigojuego>
        <serie>3</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2017</aniolanzamiento>
    </sixcollection> 
    <sixcollection>
        <id>12</id>
        <nombre>Vigil</nombre>
        <codigojuego>389772664</codigojuego>
        <serie>3</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2017</aniolanzamiento>
    </sixcollection> 
    <sixcollection>
        <id>13</id>
        <nombre>Caveira</nombre>
        <codigojuego>804629770</codigojuego>
        <serie>3</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2017</aniolanzamiento>
    </sixcollection> 
    <sixcollection>
        <id>14</id>
        <nombre>Ela</nombre>
        <codigojuego>111772149</codigojuego>
        <serie>3</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2017</aniolanzamiento>
    </sixcollection>
    <sixcollection>
        <id>15</id>
        <nombre>Twitch</nombre>
        <codigojuego>860696790</codigojuego>
        <serie>3</serie>
        <pvp>20.00</pvp>
        <aniolanzamiento>2017</aniolanzamiento>
    </sixcollection>
</BDsixcollection>
