=== AdriMG10/AdrianMerino_UD4_LMSGI/Practicas_CFGS/practicas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="practicas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nif" type="nifTipo"/>
                            <xs:element name="resultado" type="resultadoTipo"/>
                            <xs:element name="observaciones" type="observacionesTipo" minOccurs="0"/>
                            <xs:choice>
                                <xs:element name="ip" type="xs:string"/>
                                <xs:element name="mac" type="xs:string"/>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="nifTipo">
        <xs:restriction base="xs:string">
        <xs:pattern value="\d{8}[a-zA-Z]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="resultadoTipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Apto"/>
            <xs:enumeration value="No Apto"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="observacionesTipo" mixed="true">
        <xs:sequence>
            <xs:element name="anhos" type="xs:integer"/>
            <xs:element name="poblacion" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== AdriMG10/AdrianMerino_UD4_LMSGI/Practicas_CFGS/practicasXSD.xml
<?xml version="1.0" encoding="utf-8"?>
<practicas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="practicas.xsd">
	<alumno>
		<nif>28764534S</nif>
		<resultado>Apto</resultado>
		<observaciones>Este alumno tiene <anhos>20</anhos>años y vive en <poblacion>Prado del Rey</poblacion></observaciones>
		<ip>192.168.1.101</ip> <!-- Los alumnos tienen IP o MAC pero no ambas -->
	</alumno>
	<alumno>
		<nif>72826636B</nif>
		<resultado>No Apto</resultado>
		<mac>56:FE:45:CA:45:12</mac>
	</alumno>
	<alumno>
		<nif>38375739D</nif>
		<resultado>Apto</resultado>
		<observaciones>Este alumno tiene <anhos>22</anhos>años y vive en <poblacion>Ubrique</poblacion></observaciones>
		<mac>E6:69:63:8E:2F:56</mac> 
	</alumno>
	<alumno>
		<nif>44567291F</nif>
		<resultado>Apto</resultado>
		<ip>192.168.1.191</ip> 
	</alumno>
	<alumno>
		<nif>89708339J</nif>
		<resultado>Apto</resultado>
		<observaciones>Este alumno tiene <anhos>25</anhos>años y vive en <poblacion>Villamartín</poblacion></observaciones>
		<mac>3B:FA:62:EB:92:7F
		</mac>
	</alumno>
	<alumno>
		<nif>39103061W</nif>
		<resultado>No Apto</resultado>
		<ip>192.168.1.159</ip> 
	</alumno>
	<alumno>
		<nif>98905984G</nif>
		<resultado>Apto</resultado>
		<ip>192.168.1.199</ip> 
	</alumno>
	<alumno>
		<nif>11527178S</nif>
		<resultado>Apto</resultado>
		<observaciones>Este alumno tiene <anhos>19</anhos>años y vive en <poblacion>Prado del Rey</poblacion></observaciones>
		<mac>B0:72:C2:F6:0B:57</mac>
	</alumno>
	<alumno>
		<nif>63153938D</nif>
		<resultado>No Apto</resultado>
		<ip>192.168.1.123</ip> 
	</alumno>
	<alumno>
		<nif>08203820L</nif>
		<resultado>No Apto</resultado>
		<mac>31:CF:DB:88:81:5A</mac> 
	</alumno>
	<alumno>
		<nif>58763050M</nif>
		<resultado>Apto</resultado>
		<observaciones>Este alumno tiene <anhos>20</anhos>años y vive en <poblacion>Arcos de la Frontera</poblacion></observaciones>
		<ip>192.168.1.117</ip> 
	</alumno>
</practicas>
