=== AdriMG10/AdrianMerino_UD4_LMSGI/Concesionario/concesionario2.dtd
<!ELEMENT concesionario (coches*)>
<!ELEMENT coches (coche*)>
<!ELEMENT coche (codigoCoche, marca, modelo, matricula, potencia, plazas, numPuertas, consumos)>
<!ELEMENT codigoCoche (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numPuertas (#PCDATA)>
<!ELEMENT consumos (consumoCiudad, consumoCarretera, consumoMedio)>
<!ELEMENT consumoCiudad (#PCDATA)>
<!ELEMENT consumoCarretera (#PCDATA)>
<!ELEMENT consumoMedio (#PCDATA)>

=== AdriMG10/AdrianMerino_UD4_LMSGI/Concesionario/concesionario2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "concesionario2.dtd">
<concesionario>
    <coches>
        <coche>
            <codigoCoche>00001</codigoCoche>
            <marca>Renault</marca>
            <modelo>Captur</modelo>
            <matricula>8734DTB</matricula>
            <potencia>110</potencia>
            <plazas>5</plazas>
            <numPuertas>5</numPuertas>
            <consumos>
                <consumoCiudad>5.4</consumoCiudad>
                <consumoCarretera>5.9</consumoCarretera>
                <consumoMedio>4.7</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00002</codigoCoche>
            <marca>Peugeot</marca>
            <modelo>207</modelo>
            <matricula>4601DGG</matricula>
            <potencia>85</potencia>
            <plazas>5</plazas>
            <numPuertas>5</numPuertas>
            <consumos>
                <consumoCiudad>8.6</consumoCiudad>
                <consumoCarretera>4.9</consumoCarretera>
                <consumoMedio>6.3</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00003</codigoCoche>
            <marca>Renault</marca>
            <modelo>Clio</modelo>
            <matricula>2628FCB</matricula>
            <potencia>90</potencia>
            <plazas>4</plazas>
            <numPuertas>3</numPuertas>
            <consumos>
                <consumoCiudad>4.5</consumoCiudad>
                <consumoCarretera>3.5</consumoCarretera>
                <consumoMedio>4.0</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00004</codigoCoche>
            <marca>BMW</marca>
            <modelo>525d</modelo>
            <matricula>1865LJL</matricula>
            <potencia>192</potencia>
            <plazas>5</plazas>
            <numPuertas>5</numPuertas>
            <consumos>
                <consumoCiudad>9.3</consumoCiudad>
                <consumoCarretera>5.3</consumoCarretera>
                <consumoMedio>6.7</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00005</codigoCoche>
            <marca>Seat</marca>
            <modelo>Toledo</modelo>
            <matricula>6491NCD</matricula>
            <potencia>105</potencia>
            <plazas>5</plazas>
            <numPuertas>4</numPuertas>
            <consumos>
                <consumoCiudad>6.8</consumoCiudad>
                <consumoCarretera>4.3</consumoCarretera>
                <consumoMedio>5.2</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00006</codigoCoche>
            <marca>Ford</marca>
            <modelo>Kuga</modelo>
            <matricula>5165CJF</matricula>
            <potencia>120</potencia>
            <plazas>5</plazas>
            <numPuertas>5</numPuertas>
            <consumos>
                <consumoCiudad>7.8</consumoCiudad>
                <consumoCarretera>5.3</consumoCarretera>
                <consumoMedio>6.2</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00007</codigoCoche>
            <marca>Dacia</marca>
            <modelo>Sandero</modelo>
            <matricula>9058LKB</matricula>
            <potencia>78</potencia>
            <plazas>5</plazas>
            <numPuertas>5</numPuertas>
            <consumos>
                <consumoCiudad>6.6</consumoCiudad>
                <consumoCarretera>4.6</consumoCarretera>
                <consumoMedio>5.4</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00008</codigoCoche>
            <marca>Volkswagen</marca>
            <modelo>Golf R</modelo>
            <matricula>8445PLD</matricula>
            <potencia>320</potencia>
            <plazas>5</plazas>
            <numPuertas>5</numPuertas>
            <consumos>
                <consumoCiudad>8.51</consumoCiudad>
                <consumoCarretera>6.91</consumoCarretera>
                <consumoMedio>7.59</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00009</codigoCoche>
            <marca>Mazda</marca>
            <modelo>MX5</modelo>
            <matricula>9543MRT</matricula>
            <potencia>160</potencia>
            <plazas>2</plazas>
            <numPuertas>2</numPuertas>
            <consumos>
                <consumoCiudad>6.5</consumoCiudad>
                <consumoCarretera>4.9</consumoCarretera>
                <consumoMedio>5.6</consumoMedio>
            </consumos>
        </coche>
        <coche>
            <codigoCoche>00010</codigoCoche>
            <marca>Audi</marca>
            <modelo>TTS Coup√©</modelo>
            <matricula>0137MNK</matricula>
            <potencia>306</potencia>
            <plazas>2</plazas>
            <numPuertas>2</numPuertas>
            <consumos>
                <consumoCiudad>11.1</consumoCiudad>
                <consumoCarretera>6.3</consumoCarretera>
                <consumoMedio>8.1</consumoMedio>
            </consumos>
        </coche>
    </coches>
</concesionario>
